image: maven:3.3.9-jdk-8

before_script:
    - 'sed -i "s@MVN_USERNAME@${MVN_USERNAME}@g" maven-settings/settings.xml'
    - 'sed -i "s@MVN_PASSWORD@${MVN_PASSWORD}@g" maven-settings/settings.xml'
    - 'sed -i "s@MVN_MASTER@${MVN_MASTER}@g" maven-settings/settings-security.xml'

build:
  script:
    - "mvn -Dsettings.security=maven-settings/settings-security.xml -s maven-settings/settings.xml -B clean package"
  artifacts:
    paths:
      - target/*.jar
