sql:
  url: jdbc:mysql://address:3306/Database
  user: root
  password: password
server-type: Unknown
instance-name: ServerName
citadelURL: ws://localhost:3000
isDefaultSidebarEnabled: true
debug: false
citadelAndSqlDisabled: false