sql:
  url: jdbc:mysql://address:3306/Database
  user: root
  password: password
server-type: Unknown
instance-name: ServerName
dashboardURL: ws://socket.dashboard.playground.palace.network:7892
isDefaultSidebarEnabled: true
debug: false
dashboardAndSqlDisabled: false