name: Core
version: 1.3.1
depend: [ProtocolLib]
main: com.palacemc.core.Core
commands:
  list:
    description: List online players
    permission: arcade.bypass
    permission-message: ยง4You do not have permission to use this command!
  plugins:
    description: List plugins
    permission: arcade.bypass
    permission-message: ยง4You do not have permission to use this command!
  safestop:
    description: Safely stop the server
    permission: arcade.bypass
    permission-message: ยง4You do not have permission to use this command!
